// #region Modal
export enum ModalTypeEnum {
  COMPANY_MODAL = "COMPANY_MODAL",
  TRAINING_MODAL = "TRAINING_MODAL",
  USER_MODAL = "USER_MODAL",
  SIFARNIK_MODAL = "SIFARNIK_MODAL",
  PAYMENT_MODAL = "PAYMENT_MODAL",
  TOURNAMENT_MODAL = "TOURNAMENT_MODAL",
  CONTRACT_MODAL = "CONTRACT_MODAL",
  SEASON_MODAL = "SEASON_MODAL",
  MEMBERSHIP_MODAL = "MEMBERSHIP_MODAL",
  ADD_SEGMENTE_MODAL = "ADD_SEGMENTE_MODAL",
}
