// #region Modal
export enum ModalTypeEnum {
  COMPANY_MODAL = "COMPANY_MODAL",
  TRAINING_MODAL = "TRAINING_MODAL",
  USER_MODAL = "USER_MODAL",
  SIFARNIK_MODAL = "SIFARNIK_MODAL",
  PAYMENT_MODAL = "PAYMENT_MODAL",
  QUARTER_MODAL = "QUARTER_MODAL",
  QUARTER_ADD_USER_MODAL = "QUARTER_ADD_USER_MODAL",
  TOURNAMENT_MODAL = "TOURNAMENT_MODAL",
}
